'use client';

import { useState } from 'react';
import Image from 'next/image';
import { ArrowUpRight, BriefcaseBusiness, Building2, Check, ChevronRight, FileText, Gavel, Globe2, Landmark, MessageCircle, Phone, Search, ShieldCheck, Siren, WalletCards } from 'lucide-react';

const authorities = [
  { name: 'Abu Dhabi Civil Defence Authority', image: '/images/partners/abu-dhabi-civil-defence-authority.jpg' },
  { name: 'Federal Authority for Identity, Citizenship, Customs & Port Security', image: '/images/partners/federal-authority-identity-citizenship-customs-port-security.jpg' },
  { name: 'Abu Dhabi Department of Municipalities and Transport', image: '/images/partners/abu-dhabi-department-municipalities-transport.jpg' },
  { name: 'Abu Dhabi Judicial Department', image: '/images/partners/abu-dhabi-judicial-department.png' },
  { name: 'Ministry of Human Resources and Emiratisation', image: '/images/partners/ministry-of-human-resources-emiratisation.jpg' },
  { name: 'TAMM Abu Dhabi Government Services', image: '/images/partners/tamm-abu-dhabi-government-services.png' },
  { name: 'Abu Dhabi Police', image: '/images/partners/abu-dhabi-police.png' },
  { name: 'Abu Dhabi Department of Economic Development', image: '/images/partners/abu-dhabi-department-economic-development.png' },
  { name: 'Ministry of Justice', image: '/images/partners/ministry-of-justice.png' },
  { name: 'Dubai Public Prosecution', image: '/images/partners/dubai-public-prosecution.jpg' },
  { name: 'Q Mobility', image: '/images/partners/q-mobility.svg' },
  { name: 'Ministry of Interior', image: '/images/partners/ministry-of-interior.jpg' },
  { name: 'Abu Dhabi Department of Health', image: '/images/partners/abu-dhabi-department-health.png' },
  { name: 'Dubai Courts', image: '/images/partners/dubai-courts.jpg' },
  { name: 'Abu Dhabi Mobility', image: '/images/partners/abu-dhabi-mobility.jpg' },
  { name: 'General Directorate of Residency and Foreigners Affairs Dubai', image: '/images/partners/gdrfa-dubai.png' },
];

const content = {
  en: {
    dir: 'ltr', label: 'English', other: 'العربية', otherHref: '/ar', nav: ['Services', 'How it works', 'About us', 'Contact'],
    eyebrow: 'Qemmat Al Majd Business Services', title: <>Your trusted partner for <em>government</em> & legal services.</>, intro: 'Clear guidance, careful preparation and dependable follow-through for the moments that matter to your business and family.', explore: 'Explore services', request: 'Submit a request', trackLabel: 'Track an existing request', trackPlaceholder: 'Enter reference, e.g. QM-2026-000001', trackButton: 'Track', tracking: 'Enter a reference number to check your request.', stats: [['15+', 'Years of experience'], ['25k+', 'Requests supported'], ['7', 'Service areas']],
    serviceEyebrow: 'A single point of support', serviceTitle: 'The right route through the details.', serviceText: 'From a first document check to the final submission, our team keeps the process clear, organized and moving.', categories: [{ icon: Landmark, title: 'Government services', text: 'TAMM, police, municipality and official application support.' }, { icon: Gavel, title: 'Courts & prosecution', text: 'Case registration, enforcement, notary and judicial assistance.' }, { icon: Globe2, title: 'Immigration', text: 'Visa, residency and entry permit administration.' }, { icon: BriefcaseBusiness, title: 'Business setup', text: 'Company formation, licensing and business support.' }, { icon: Siren, title: 'Traffic & parking', text: 'Traffic, vehicle, Mawaqif, Darb and Salik services.' }, { icon: ShieldCheck, title: 'Insurance & documents', text: 'Health insurance and sensitive document support.' }], viewAll: 'View all services', authorityEyebrow: 'Government entities', authorityTitle: 'Authorities relevant to our services', authorityText: 'Depending on your request, services may involve these government entities and platforms.',
    whyEyebrow: 'Why Qemmat Al Majd', whyTitle: 'Professional help, without the uncertainty.', reasons: [{ title: 'Accurate preparation', text: 'We review the details and requirements before your application moves forward.' }, { title: 'Confidential by design', text: 'Your documents are handled with care and access is limited to the people who need it.' }, { title: 'One clear conversation', text: 'A dedicated team keeps you informed through every meaningful step.' }],
    stepsEyebrow: 'A simpler process', stepsTitle: 'From question to completion.', steps: [['01', 'Tell us what you need', 'Choose a service or send us a message with the details.'], ['02', 'Prepare with confidence', 'We confirm requirements, documents, timing and next steps.'], ['03', 'Track your progress', 'Receive a reference number and clear updates until completion.']],
    quoteTitle: 'Let’s get the paperwork moving.', quoteText: 'Tell us what you are trying to complete. We will help you understand the next best step.', start: 'Start a request', whatsapp: 'Chat on WhatsApp', contactEyebrow: 'Here when you need us', contactTitle: 'Let’s make the next step clear.', contactText: 'Independent business-services support across the UAE. We are not a government entity and do not represent government authorities.', whatsappLabel: 'WhatsApp', phoneLabel: 'Mobile phone', officeLabel: 'Office', mapTitle: 'Find us in Abu Dhabi', disclaimer: 'Qemmat Al Majd Business Services is an independent business-services provider and is not a government entity. We assist customers with preparing and submitting applications through the appropriate official channels.', privacy: 'Privacy policy', terms: 'Terms & conditions'
  },
  ar: {
    dir: 'rtl', label: 'العربية', other: 'English', otherHref: '/en', nav: ['الخدمات', 'كيف نعمل', 'من نحن', 'تواصل معنا'],
    eyebrow: 'قمة المجد لخدمات رجال الأعمال', title: <>شريككم الموثوق في <em>الخدمات</em> الحكومية والقانونية.</>, intro: 'إرشاد واضح، وتجهيز دقيق، ومتابعة موثوقة في الخطوات التي تهم أعمالكم وحياتكم.', explore: 'استكشف الخدمات', request: 'تقديم طلب', trackLabel: 'تتبع طلباً قائماً', trackPlaceholder: 'أدخل الرقم المرجعي، مثال QM-2026-000001', trackButton: 'تتبع', tracking: 'أدخل الرقم المرجعي للتحقق من حالة طلبك.', stats: [['+15', 'عاماً من الخبرة'], ['+25 ألف', 'طلب تمت مساعدته'], ['7', 'مجالات للخدمة']],
    serviceEyebrow: 'نقطة دعم واحدة', serviceTitle: 'الطريق الصحيح وسط التفاصيل.', serviceText: 'من مراجعة المستندات الأولى وحتى التقديم النهائي، نحرص على وضوح الإجراءات وتنظيمها واستمرارها.', categories: [{ icon: Landmark, title: 'الخدمات الحكومية', text: 'خدمات تم، والشرطة، والبلدية ودعم الطلبات الرسمية.' }, { icon: Gavel, title: 'المحاكم والنيابة', text: 'تسجيل القضايا والتنفيذ والكاتب العدل والمساعدة القضائية.' }, { icon: Globe2, title: 'خدمات الهجرة', text: 'إجراءات التأشيرات والإقامة وتصاريح الدخول.' }, { icon: BriefcaseBusiness, title: 'تأسيس الأعمال', text: 'تأسيس الشركات والتراخيص ودعم الأعمال.' }, { icon: Siren, title: 'المرور والمواقف', text: 'خدمات المرور والمركبات ومواقف ودرب وسالك.' }, { icon: ShieldCheck, title: 'التأمين والمستندات', text: 'التأمين الصحي ودعم المستندات الحساسة.' }], viewAll: 'عرض جميع الخدمات', authorityEyebrow: 'الجهات الحكومية', authorityTitle: 'جهات ذات صلة بخدماتنا', authorityText: 'قد تتضمن الخدمات هذه الجهات والمنصات الحكومية بحسب نوع الطلب.',
    whyEyebrow: 'لماذا قمة المجد', whyTitle: 'مساعدة احترافية، بلا غموض.', reasons: [{ title: 'تجهيز دقيق', text: 'نراجع التفاصيل والمتطلبات قبل أن يتقدم طلبكم.' }, { title: 'سرية في كل خطوة', text: 'نتعامل مع مستنداتكم بعناية ونحصر الوصول على المختصين.' }, { title: 'تواصل واضح', text: 'يبقيكم فريق متخصص على اطلاع بكل خطوة مهمة.' }],
    stepsEyebrow: 'إجراءات أبسط', stepsTitle: 'من الاستفسار إلى الإنجاز.', steps: [['01', 'أخبرنا بما تحتاج', 'اختر الخدمة أو أرسل لنا رسالة بالتفاصيل.'], ['02', 'استعد بثقة', 'نؤكد المتطلبات والمستندات والمدة والخطوات التالية.'], ['03', 'تابع تقدمك', 'تحصل على رقم مرجعي وتحديثات واضحة حتى الإنجاز.']],
    quoteTitle: 'لنبدأ بإنجاز معاملاتكم.', quoteText: 'أخبرنا بما تحاول إنجازه وسنساعدك في فهم الخطوة الأفضل التالية.', start: 'ابدأ طلباً', whatsapp: 'تواصل عبر واتساب', contactEyebrow: 'نحن هنا لمساعدتكم', contactTitle: 'لنجعل الخطوة التالية واضحة.', contactText: 'دعم مستقل لخدمات الأعمال في دولة الإمارات. لسنا جهة حكومية ولا نمثل الجهات الحكومية.', whatsappLabel: 'واتساب', phoneLabel: 'الهاتف المحمول', officeLabel: 'المكتب', mapTitle: 'موقعنا في أبوظبي', disclaimer: 'قمة المجد لخدمات رجال الأعمال مقدم مستقل لخدمات الأعمال وليست جهة حكومية. نساعد العملاء في إعداد الطلبات وتقديمها عبر القنوات الرسمية المختصة.', privacy: 'سياسة الخصوصية', terms: 'الشروط والأحكام'
  }
} as const;

export default function Home({ params }: { params: { locale: string } }) {
  const lang = params.locale === 'ar' ? 'ar' : 'en';
  const t = content[lang];
  const [reference, setReference] = useState('');
  const [message, setMessage] = useState('');
  const whatsappHref = 'https://wa.me/971566579033';

  function trackRequest() { setMessage(reference.trim() ? `We found your request ${reference.trim()}. A secure tracking view will be available after API connection.` : t.tracking); }

  return <main dir={t.dir}>
    <section className="hero" id="home">
      <div className="hero-grid" />
      <header className="header container"><a className="logo" href="#home"><span className="logo-mark"><span>ق</span></span><span>QEMMAT AL MAJD<small>{t.label === 'English' ? 'BUSINESS SERVICES' : 'خدمات رجال الأعمال'}</small></span></a><nav className="nav">{t.nav.map((item, index) => <a key={item} href={['#services', '#process', '#about', '#contact'][index]}>{item}</a>)}<a className="lang" href={t.otherHref}>{t.other}</a></nav></header>
      <div className="hero-content container"><div><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><p className="hero-copy">{t.intro}</p><div className="actions"><a className="btn btn-primary" href="#services">{t.explore}<ArrowUpRight size={16} /></a><a className="btn btn-outline" href="#contact">{t.request}</a></div><div className="stat-strip">{t.stats.map(([value, label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div><div className="hero-panel"><label>{t.trackLabel}</label><div className="track-row"><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder={t.trackPlaceholder} /><button aria-label={t.trackButton} onClick={trackRequest}><Search size={18} /></button></div><p className="panel-note">{message}</p></div></div>
    </section>

    <section className="section light-section" id="services"><div className="container"><div className="section-heading"><div className="eyebrow">{t.serviceEyebrow}</div><h2>{t.serviceTitle}</h2><p>{t.serviceText}</p></div><div className="category-grid">{t.categories.map(({ icon: Icon, title, text }) => <article className="category" key={title}><div><div className="category-icon"><Icon size={20} strokeWidth={1.5} /></div><h3>{title}</h3><p>{text}</p></div><a href="#contact">{t.viewAll}<ChevronRight size={14} /></a></article>)}</div></div></section>
    <section className="section authorities-section"><div className="container"><div className="section-heading"><div className="eyebrow">{t.authorityEyebrow}</div><h2>{t.authorityTitle}</h2><p>{t.authorityText}</p></div><ul className="authority-grid">{authorities.map(({ name, image }) => <li className="authority-logo" key={image}><Image src={image} alt={name} width={220} height={100} sizes="(max-width: 520px) 44vw, (max-width: 820px) 28vw, 15vw" /></li>)}</ul></div></section>
    <section className="section" id="about"><div className="container split"><div className="about-intro"><div className="section-heading"><div className="eyebrow">{t.whyEyebrow}</div><h2>{t.whyTitle}</h2></div><Image className="team-photo" src="/images/team/team-portrait-01.jpeg" alt={t.label === 'English' ? 'Qemmat Al Majd team member in the office' : 'أحد أعضاء فريق قمة المجد في المكتب'} width={922} height={1152} sizes="(max-width: 820px) 100vw, 36vw" /></div><div className="list">{t.reasons.map((reason, index) => <div className="list-item" key={reason.title}><span className="list-number">0{index + 1}</span><div><h3>{reason.title}</h3><p>{reason.text}</p></div></div>)}</div></div></section>
    <section className="section light-section" id="process"><div className="container"><div className="section-heading"><div className="eyebrow">{t.stepsEyebrow}</div><h2>{t.stepsTitle}</h2></div><div className="category-grid">{t.steps.map(([number, title, text]) => <article className="category" key={number}><div className="eyebrow">{number}</div><div><h3>{title}</h3><p>{text}</p></div><Check size={18} color="var(--gold)" /></article>)}</div></div></section>
    <section className="section container"><div className="quote"><div className="eyebrow">{t.request}</div><h2>{t.quoteTitle}</h2><p>{t.quoteText}</p><div className="actions"><a className="btn btn-primary" href="#contact">{t.start}<ArrowUpRight size={16} /></a><a className="btn btn-outline" href={whatsappHref} target="_blank">{t.whatsapp}<MessageCircle size={16} /></a></div></div></section>
    <section className="section contact" id="contact"><div className="container"><div className="section-heading"><div className="eyebrow">{t.contactEyebrow}</div><h2>{t.contactTitle}</h2><p>{t.contactText}</p></div><div className="contact-content"><div className="contact-row"><a className="contact-link" href={whatsappHref} target="_blank" rel="noreferrer"><MessageCircle size={18} /><span><small>{t.whatsappLabel}</small><strong>+971 56 657 9033</strong></span></a><a className="contact-link" href="tel:+971589271774"><Phone size={18} /><span><small>{t.phoneLabel}</small><strong>+971 58 927 1774</strong></span></a><a className="contact-link" href="tel:+97124469035"><Building2 size={18} /><span><small>{t.officeLabel}</small><strong>+971 2 446 9035</strong></span></a><a className="contact-link" href="mailto:hello@qemmat-almajd.ae"><FileText size={18} /><span><small>Email</small><strong>hello@qemmat-almajd.ae</strong></span></a></div><div className="contact-map"><h3>{t.mapTitle}</h3><iframe title={t.mapTitle} src="https://www.google.com/maps?q=CFF2%2B9XJ+Abu+Dhabi,+United+Arab+Emirates&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></div></section>
    <footer className="footer"><div className="container footer-row"><div className="disclaimer">{t.disclaimer}</div><div><a href="#">{t.privacy}</a> &nbsp; · &nbsp; <a href="#">{t.terms}</a></div></div></footer><div className="mobile-bar"><a className="btn btn-primary" href={whatsappHref} target="_blank"><MessageCircle size={17} /> {t.whatsapp}</a></div>
  </main>;
}
