<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id(); $table->string('name'); $table->string('email')->unique(); $table->timestamp('email_verified_at')->nullable(); $table->string('password'); $table->string('mobile', 30)->nullable()->unique(); $table->rememberToken(); $table->timestamps(); $table->softDeletes();
        });
        Schema::create('personal_access_tokens', function (Blueprint $table) { $table->id(); $table->morphs('tokenable'); $table->string('name'); $table->string('token', 64)->unique(); $table->text('abilities')->nullable(); $table->timestamp('last_used_at')->nullable(); $table->timestamp('expires_at')->nullable(); $table->timestamps(); });
        Schema::create('roles', fn (Blueprint $t) => [$t->id(), $t->string('name')->unique(), $t->string('guard_name')->default('web'), $t->timestamps()]);
        Schema::create('permissions', fn (Blueprint $t) => [$t->id(), $t->string('name')->unique(), $t->string('guard_name')->default('web'), $t->timestamps()]);
        Schema::create('role_has_permissions', function (Blueprint $t) { $t->foreignId('permission_id')->constrained()->cascadeOnDelete(); $t->foreignId('role_id')->constrained()->cascadeOnDelete(); $t->primary(['permission_id', 'role_id']); });
        Schema::create('model_has_roles', function (Blueprint $t) { $t->unsignedBigInteger('role_id'); $t->string('model_type'); $t->unsignedBigInteger('model_id'); $t->index(['model_id', 'model_type']); $t->foreign('role_id')->references('id')->on('roles')->cascadeOnDelete(); $t->primary(['role_id', 'model_id', 'model_type']); });
        Schema::create('model_has_permissions', function (Blueprint $t) { $t->unsignedBigInteger('permission_id'); $t->string('model_type'); $t->unsignedBigInteger('model_id'); $t->index(['model_id', 'model_type']); $t->foreign('permission_id')->references('id')->on('permissions')->cascadeOnDelete(); $t->primary(['permission_id', 'model_id', 'model_type']); });
        Schema::create('customers', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete(); $t->string('nationality')->nullable(); $t->string('emirates_id')->nullable(); $t->string('preferred_language', 5)->default('en'); $t->string('preferred_communication')->default('whatsapp'); $t->timestamps(); $t->softDeletes(); });
        Schema::create('staff_profiles', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete(); $t->string('job_title')->nullable(); $t->string('employee_code')->unique(); $t->boolean('active')->default(true); $t->timestamps(); });
        Schema::create('service_categories', function (Blueprint $t) { $t->id(); $t->string('name_en'); $t->string('name_ar'); $t->string('slug')->unique(); $t->text('description_en')->nullable(); $t->text('description_ar')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->boolean('featured')->default(false); $t->boolean('published')->default(true); $t->softDeletes(); $t->timestamps(); });
        Schema::create('services', function (Blueprint $t) { $t->id(); $t->foreignId('service_category_id')->constrained()->restrictOnDelete(); $t->string('name_en'); $t->string('name_ar'); $t->string('slug')->unique(); $t->text('short_description_en')->nullable(); $t->text('short_description_ar')->nullable(); $t->longText('description_en')->nullable(); $t->longText('description_ar')->nullable(); $t->decimal('government_fee', 12, 2)->nullable(); $t->decimal('service_fee', 12, 2)->nullable(); $t->unsignedInteger('processing_days')->nullable(); $t->text('eligibility_en')->nullable(); $t->text('eligibility_ar')->nullable(); $t->text('notes_en')->nullable(); $t->text('notes_ar')->nullable(); $t->boolean('featured')->default(false); $t->boolean('published')->default(true); $t->softDeletes(); $t->timestamps(); $t->index(['published', 'featured']); });
        Schema::create('service_requirements', function (Blueprint $t) { $t->id(); $t->foreignId('service_id')->constrained()->cascadeOnDelete(); $t->string('name_en'); $t->string('name_ar'); $t->boolean('required')->default(true); $t->string('allowed_mimes')->default('pdf,jpg,jpeg,png'); $t->unsignedInteger('max_kb')->default(10240); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('service_faqs', function (Blueprint $t) { $t->id(); $t->foreignId('service_id')->constrained()->cascadeOnDelete(); $t->string('question_en'); $t->string('question_ar'); $t->text('answer_en'); $t->text('answer_ar'); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('service_requests', function (Blueprint $t) { $t->id(); $t->string('reference')->unique(); $t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('service_id')->constrained()->restrictOnDelete(); $t->string('full_name'); $t->string('mobile', 30); $t->string('email'); $t->string('nationality')->nullable(); $t->string('emirates_id')->nullable(); $t->string('preferred_language', 5)->default('en'); $t->string('preferred_communication')->default('whatsapp'); $t->text('details'); $t->string('status')->default('new')->index(); $t->boolean('consent_at')->default(false); $t->timestamps(); $t->softDeletes(); $t->index(['mobile', 'email']); });
        Schema::create('request_status_histories', function (Blueprint $t) { $t->id(); $t->foreignId('service_request_id')->constrained()->cascadeOnDelete(); $t->foreignId('staff_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('previous_status')->nullable(); $t->string('new_status'); $t->text('customer_note')->nullable(); $t->text('internal_note')->nullable(); $t->timestamp('created_at')->useCurrent(); $t->index(['service_request_id', 'created_at']); });
        Schema::create('request_documents', function (Blueprint $t) { $t->id(); $t->foreignId('service_request_id')->constrained()->cascadeOnDelete(); $t->foreignId('service_requirement_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete(); $t->string('original_name'); $t->string('stored_name')->unique(); $t->string('disk')->default('local'); $t->string('path'); $t->string('mime_type'); $t->unsignedBigInteger('size'); $t->string('status')->default('pending_scan'); $t->timestamp('expires_at')->nullable(); $t->timestamps(); });
        Schema::create('request_messages', function (Blueprint $t) { $t->id(); $t->foreignId('service_request_id')->constrained()->cascadeOnDelete(); $t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete(); $t->text('body'); $t->boolean('customer_visible')->default(true); $t->timestamp('read_at')->nullable(); $t->timestamps(); });
        Schema::create('quotations', function (Blueprint $t) { $t->id(); $t->foreignId('service_request_id')->constrained()->cascadeOnDelete(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->string('number')->unique(); $t->decimal('subtotal', 12, 2)->default(0); $t->decimal('tax', 12, 2)->default(0); $t->decimal('total', 12, 2)->default(0); $t->string('status')->default('draft'); $t->date('valid_until')->nullable(); $t->timestamps(); });
        Schema::create('quotation_items', function (Blueprint $t) { $t->id(); $t->foreignId('quotation_id')->constrained()->cascadeOnDelete(); $t->string('description'); $t->unsignedInteger('quantity')->default(1); $t->decimal('unit_price', 12, 2); $t->timestamps(); });
        Schema::create('invoices', function (Blueprint $t) { $t->id(); $t->foreignId('service_request_id')->constrained()->cascadeOnDelete(); $t->string('number')->unique(); $t->decimal('subtotal', 12, 2)->default(0); $t->decimal('tax', 12, 2)->default(0); $t->decimal('total', 12, 2)->default(0); $t->string('status')->default('unpaid'); $t->timestamps(); });
        Schema::create('invoice_items', function (Blueprint $t) { $t->id(); $t->foreignId('invoice_id')->constrained()->cascadeOnDelete(); $t->string('description'); $t->unsignedInteger('quantity')->default(1); $t->decimal('unit_price', 12, 2); $t->timestamps(); });
        Schema::create('payments', function (Blueprint $t) { $t->id(); $t->foreignId('invoice_id')->constrained()->cascadeOnDelete(); $t->decimal('amount', 12, 2); $t->string('gateway')->default('manual'); $t->string('transaction_id')->nullable(); $t->string('status')->default('pending'); $t->timestamp('paid_at')->nullable(); $t->timestamps(); });
        Schema::create('faqs', function (Blueprint $t) { $t->id(); $t->string('question_en'); $t->string('question_ar'); $t->text('answer_en'); $t->text('answer_ar'); $t->boolean('published')->default(true); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('team_members', function (Blueprint $t) { $t->id(); $t->string('name_en'); $t->string('name_ar'); $t->string('role_en')->nullable(); $t->string('role_ar')->nullable(); $t->text('bio_en')->nullable(); $t->text('bio_ar')->nullable(); $t->string('photo_path')->nullable(); $t->boolean('published')->default(true); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('contact_enquiries', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('email'); $t->string('mobile', 30)->nullable(); $t->string('subject')->nullable(); $t->text('message'); $t->string('status')->default('new'); $t->timestamps(); });
        Schema::create('pages', function (Blueprint $t) { $t->id(); $t->string('slug')->unique(); $t->string('title_en'); $t->string('title_ar'); $t->longText('body_en'); $t->longText('body_ar'); $t->string('seo_title_en')->nullable(); $t->string('seo_title_ar')->nullable(); $t->text('seo_description_en')->nullable(); $t->text('seo_description_ar')->nullable(); $t->boolean('published')->default(true); $t->timestamps(); });
        Schema::create('settings', function (Blueprint $t) { $t->id(); $t->string('key')->unique(); $t->text('value')->nullable(); $t->string('type')->default('string'); $t->timestamps(); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->string('auditable_type')->nullable(); $t->unsignedBigInteger('auditable_id')->nullable(); $t->string('ip_address', 45)->nullable(); $t->json('metadata')->nullable(); $t->timestamp('created_at')->useCurrent(); $t->index(['auditable_type', 'auditable_id']); });
        Schema::create('document_access_logs', function (Blueprint $t) { $t->id(); $t->foreignId('document_id')->constrained('request_documents')->cascadeOnDelete(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->string('ip_address', 45)->nullable(); $t->timestamp('created_at')->useCurrent(); });
        Schema::create('password_reset_tokens', fn (Blueprint $t) => [$t->string('email')->primary(), $t->string('token'), $t->timestamp('created_at')->nullable()]);
        Schema::create('sessions', function (Blueprint $t) { $t->string('id')->primary(); $t->foreignId('user_id')->nullable()->index(); $t->string('ip_address', 45)->nullable(); $t->text('user_agent')->nullable(); $t->text('payload'); $t->integer('last_activity')->index(); });
    }

    public function down(): void { Schema::dropIfExists('document_access_logs'); Schema::dropIfExists('audit_logs'); Schema::dropIfExists('settings'); Schema::dropIfExists('pages'); Schema::dropIfExists('contact_enquiries'); Schema::dropIfExists('team_members'); Schema::dropIfExists('faqs'); Schema::dropIfExists('payments'); Schema::dropIfExists('invoice_items'); Schema::dropIfExists('invoices'); Schema::dropIfExists('quotation_items'); Schema::dropIfExists('quotations'); Schema::dropIfExists('request_messages'); Schema::dropIfExists('request_documents'); Schema::dropIfExists('request_status_histories'); Schema::dropIfExists('service_requests'); Schema::dropIfExists('service_faqs'); Schema::dropIfExists('service_requirements'); Schema::dropIfExists('services'); Schema::dropIfExists('service_categories'); Schema::dropIfExists('staff_profiles'); Schema::dropIfExists('customers'); Schema::dropIfExists('model_has_permissions'); Schema::dropIfExists('model_has_roles'); Schema::dropIfExists('role_has_permissions'); Schema::dropIfExists('permissions'); Schema::dropIfExists('roles'); Schema::dropIfExists('sessions'); Schema::dropIfExists('password_reset_tokens'); Schema::dropIfExists('users'); }
};
