<?php
namespace Database\Seeders;
use App\Models\Service;
use App\Models\ServiceCategory;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
class DatabaseSeeder extends Seeder { public function run(): void { $permissions=['requests.view','requests.update','documents.view','documents.create','financials.manage','content.manage','users.manage']; foreach($permissions as $permission){Permission::findOrCreate($permission,'web');} foreach(['Super Administrator','Manager','Case Officer','Accountant','Content Editor'] as $role){$model=Role::findOrCreate($role,'web'); $model->syncPermissions(match($role){'Super Administrator'=>$permissions,'Manager'=>['requests.view','requests.update','documents.view','documents.create','financials.manage','content.manage'],'Case Officer'=>['requests.view','requests.update','documents.view','documents.create'],'Accountant'=>['requests.view','financials.manage'],'Content Editor'=>['content.manage']});} $admin=User::firstOrCreate(['email'=>'admin@qemmat-almajd.ae'],['name'=>'Super Administrator','password'=>Hash::make('ChangeMe123!'),'mobile'=>'0500000000','email_verified_at'=>now()]); $admin->assignRole('Super Administrator'); $categories=[['Government services','الخدمات الحكومية','government'],['Courts and prosecution','المحاكم والنيابة','courts'],['Immigration','الهجرة والإقامة','immigration'],['Labour services','خدمات العمل','labour'],['Business services','خدمات الأعمال','business'],['Traffic and parking','المرور والمواقف','traffic'],['Health insurance','التأمين الصحي','insurance']]; foreach($categories as $index=>[$en,$ar,$slug]){$category=ServiceCategory::updateOrCreate(['slug'=>$slug],['name_en'=>$en,'name_ar'=>$ar,'sort_order'=>$index,'featured'=>$index<3,'published'=>true]); $serviceNames=match($slug){'government'=>[['Abu Dhabi Government Services - TAMM','خدمات حكومة أبوظبي - تم'],['Ministry of Interior Services','خدمات وزارة الداخلية']], 'courts'=>[['Public Prosecution Requests','طلبات النيابة العامة'],['Notary Public Services','خدمات الكاتب العدل']], 'immigration'=>[['Visa applications','طلبات التأشيرات'],['Residency assistance','المساعدة في الإقامة']], 'labour'=>[['MOHRE transaction assistance','مساعدة معاملات وزارة الموارد البشرية']], 'business'=>[['Company incorporation','تأسيس الشركات'],['Trade-name reservation','حجز الاسم التجاري']], 'traffic'=>[['Traffic services','خدمات المرور'],['Mawaqif services','خدمات مواقف']], default=>[['Health-insurance assistance','مساعدة التأمين الصحي'] ]}; foreach($serviceNames as [$nameEn,$nameAr]){$slugService=\Illuminate\Support\Str::slug($nameEn); Service::updateOrCreate(['slug'=>$slugService],['service_category_id'=>$category->id,'name_en'=>$nameEn,'name_ar'=>$nameAr,'short_description_en'=>'Clear requirements and guidance from our team.','short_description_ar'=>'متطلبات واضحة وإرشاد من فريقنا.','description_en'=>'Professional assistance through the appropriate official channels.','description_ar'=>'مساعدة احترافية عبر القنوات الرسمية المختصة.','processing_days'=>5,'featured'=>true,'published'=>true]);}} } }
