<?php
namespace App\Http\Controllers;
use App\Models\Service;
use App\Models\ServiceRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class ServiceRequestController extends Controller {
 public function store(Request $request){$data=$request->validate(['service_id'=>'nullable|exists:services,id','service'=>'nullable|string|max:180','full_name'=>'required|string|max:120','name'=>'nullable|string|max:120','mobile'=>'required|string|max:30','email'=>'required|email','nationality'=>'nullable|string|max:80','emirates_id'=>'nullable|string|max:40','preferred_language'=>'nullable|in:en,ar','preferred_communication'=>'nullable|in:whatsapp,phone,email','details'=>'required|string|max:5000','consent_at'=>'sometimes|accepted','consent'=>'sometimes|accepted']); $service=isset($data['service_id']) ? Service::where('published',true)->findOrFail($data['service_id']) : Service::where('published',true)->where(fn($q)=>$q->where('name_en',$data['service']??'')->orWhere('name_ar',$data['service']??''))->firstOrFail(); $data['service_id']=$service->id; $data['full_name']=$data['full_name']??$data['name']; $data['consent_at']=true; unset($data['service'],$data['name'],$data['consent']); $result=DB::transaction(function() use($data,$request){$customer=$request->user()?->customer; return ServiceRequest::create($data+['customer_id'=>$customer?->id]);}); return response()->json($result->load(['service','latestStatus']),201); }
 public function mine(Request $request){return ServiceRequest::with(['service','latestStatus','messages'=>fn($q)=>$q->where('customer_visible',true)])->where('customer_id',$request->user()->customer?->id)->latest()->paginate(15);}
 public function track(Request $request,string $reference){$data=$request->validate(['contact'=>'required|string']); $query=ServiceRequest::with(['service','statusHistories','messages'=>fn($q)=>$q->where('customer_visible',true)])->where('reference',$reference)->where(fn($q)=>$q->where('mobile',$data['contact'])->orWhere('email',$data['contact'])); return response()->json($query->firstOrFail());}
 public function show(Request $request,ServiceRequest $serviceRequest){abort_unless($request->user()->customer?->id===$serviceRequest->customer_id || $request->user()->can('requests.view'),403); return $serviceRequest->load(['service','statusHistories','documents','messages'=>fn($q)=>$q->where('customer_visible',true)]);}
 public function updateStatus(Request $request,ServiceRequest $serviceRequest){$data=$request->validate(['status'=>'required|in:new,under_review,awaiting_documents,quotation_sent,payment_pending,in_progress,submitted_to_authority,completed,rejected,cancelled','customer_note'=>'nullable|string','internal_note'=>'nullable|string']); abort_unless($request->user()->can('requests.update'),403); $previous=$serviceRequest->status; DB::transaction(function() use($serviceRequest,$data,$request,$previous){$serviceRequest->update(['status'=>$data['status']]); $serviceRequest->statusHistories()->create(['staff_id'=>$request->user()->id,'previous_status'=>$previous,'new_status'=>$data['status'],'customer_note'=>$data['customer_note']??null,'internal_note'=>$data['internal_note']??null]);}); return $serviceRequest->fresh()->load('latestStatus');}
}
