'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';

const configuredApi = process.env.NEXT_PUBLIC_API_URL?.trim();
const api = configuredApi && /^https?:\/\//.test(configuredApi) ? configuredApi.replace(/\/$/, '') : 'http://localhost:8000/api/v1';

export default function DashboardPage({ params }: { params: { locale: string } }) {
  const arabic = params.locale === 'ar';
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [token, setToken] = useState('');
  const [requests, setRequests] = useState<Array<{ reference: string; status: string; service?: { name_en: string } }>>([]);
  const [error, setError] = useState('');
  async function login(event: FormEvent) { event.preventDefault(); setError(''); try { const body = new URLSearchParams({ email, password }); const response = await fetch(`${api}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' }, body }); const data = await response.json(); if (!response.ok) return setError(data.message || (arabic ? 'تعذر تسجيل الدخول.' : 'Unable to sign in.')); setToken(data.token); localStorage.setItem('qemmat_token', data.token); } catch { setError(arabic ? 'تعذر الاتصال بالخادم.' : 'Unable to connect to the server.'); } }
  useEffect(() => { const saved = localStorage.getItem('qemmat_token'); if (!saved) return; setToken(saved); fetch(`${api}/service-requests`, { headers: { Authorization: `Bearer ${saved}`, Accept: 'application/json' } }).then(response => { if (!response.ok) throw new Error('Request loading failed'); return response.json(); }).then(data => setRequests(data.data || [])).catch(() => { localStorage.removeItem('qemmat_token'); setToken(''); setError(arabic ? 'انتهت صلاحية الجلسة. يرجى تسجيل الدخول مرة أخرى.' : 'Your session expired. Please sign in again.'); }); }, [arabic]);
  return <main dir={arabic ? 'rtl' : 'ltr'} style={{ minHeight: '100vh', background: '#f5f7fa' }}><header style={{ background: '#0b2239', color: 'white', padding: '22px 0' }}><div className="container" style={{ display: 'flex', justifyContent: 'space-between' }}><Link href={`/${params.locale}`} style={{ fontWeight: 700 }}>QEMMAT AL MAJD</Link><Link href={arabic ? '/en/dashboard' : '/ar/dashboard'} style={{ fontSize: 13 }}>{arabic ? 'English' : 'العربية'}</Link></div></header><div className="container" style={{ padding: '62px 0', maxWidth: 850 }}>{!token ? <form onSubmit={login} style={{ maxWidth: 470, margin: '0 auto', padding: 32, background: 'white', border: '1px solid #e5e9ef' }}><div className="eyebrow">{arabic ? 'بوابة العملاء' : 'Customer portal'}</div><h1 style={{ color: '#0b2239' }}>{arabic ? 'مرحباً بعودتكم.' : 'Welcome back.'}</h1><label>{arabic ? 'البريد الإلكتروني' : 'Email'}<input required type="email" value={email} onChange={event => setEmail(event.target.value)} style={fieldStyle} /></label><label>{arabic ? 'كلمة المرور' : 'Password'}<input required type="password" value={password} onChange={event => setPassword(event.target.value)} style={fieldStyle} /></label>{error && <p style={{ color: '#a33' }}>{error}</p>}<button className="btn btn-primary" style={{ marginTop: 18 }} type="submit">{arabic ? 'تسجيل الدخول' : 'Sign in'}</button></form> : <><div className="section-heading"><div className="eyebrow">{arabic ? 'حسابي' : 'My account'}</div><h2>{arabic ? 'طلباتكم الحالية.' : 'Your current requests.'}</h2><p>{arabic ? 'تابعوا الحالة وأضيفوا المستندات المطلوبة من مكان واحد.' : 'Track status and add requested documents from one place.'}</p></div>{requests.length === 0 ? <div style={{ padding: 28, background: 'white', border: '1px solid #e5e9ef', color: '#667085' }}>{arabic ? 'لا توجد طلبات بعد.' : 'No requests yet.'}</div> : <div style={{ display: 'grid', gap: 12 }}>{requests.map(request => <article key={request.reference} style={{ display: 'flex', justifyContent: 'space-between', gap: 15, padding: 22, background: 'white', border: '1px solid #e5e9ef' }}><div><strong style={{ color: '#0b2239' }}>{request.reference}</strong><p style={{ color: '#667085', margin: '8px 0 0' }}>{request.service?.name_en}</p></div><span className="eyebrow">{request.status}</span></article>)}</div>}</>}</div></main>;
}
const fieldStyle = { display: 'block', width: '100%', marginTop: 8, marginBottom: 16, padding: '13px 14px', border: '1px solid #dce2e8', outline: 0 } as const;
